### ISSUE TITLE
Gemini API should be confirmed

### ISSUE THREAD

**Issue by pentium10** [MarianoMolina/project_alice#14]
what is this service for?
Its this Gemini Crypto or Gemini Google? 

![image](https://github.com/user-attachments/assets/a3dff366-8658-4f1f-a145-faac213b02f0)

**Comment by MarianoMolina** [comment]
Gemini crypto? No, its Google Gemini's api.

**Comment by pentium10** [comment]
the gemini.ai domain in the link is ASSOCIATED with a crypto business, its very missleading.

**Comment by MarianoMolina** [comment]
I see the confusion. The link is to api.gemini.ai, which doesn’t exist, its
a dummy url. The gemini api doesn’t allow/require a baseurl, so its
basically not relevant. You can confirm this in the code looking at:
workflow/core/api/engines/llm_engines/gemini_llm_engine
