### ISSUE TITLE
lmstudio.js

### ISSUE THREAD

**Issue by FarVision2** [MarianoMolina/project_alice#5]
I noticed in your notes referencing the LMS SDK. I would probably go ahead and tap that in or put it in the readme at some point.

I had not used LM Studio in a long time and didn't realize they had a Linux version. Couldn't find out where to get the server right away so I found a reference to a .cache directory once you had the app image at 

https://github.com/lmstudio-ai/lms?tab=readme-ov-file#installation

Which was 672 MB and confused me :) 

Then I found
https://github.com/lmstudio-ai/lmstudio.js

In my particular case, it doesn't run but that is my issue to solve. At some point, I would enjoy an external OpenAI API so I could use Obama and LMdeploy and whatnot.

Looking forward to getting this going.  I can't even tell you how many abandoned failed Agentic projects I've tried to get going.

**Comment by MarianoMolina** [comment]
Hey steve. Good shout. Definitely need to improve that. Ive even been struggling to have it work on my own macbook correctly, so Im expecting people might struggle. 

Will add it to my tasks to figure out a better way. I really appreciate the feedback btw
