### ISSUE TITLE
`docker compose` vs `docker-compose`

### ISSUE THREAD

**Issue by micklynch** [MarianoMolina/project_alice#6]
Some ppl (e.g. me) only have 'docker compose' on their machines and not docker-compose.

**Comment by MarianoMolina** [comment]
I honestly wasn't aware of this so thank you for bringing it up. 

Is there a way to programatically check which docker cli you have installed? 

The easiest suggestion for now is to adjust this line in run.py:


    subprocess.run(["docker-compose", "up"])
    
  To use docker compose instead.

**Comment by DeanAyalon** [comment]
I wouldn't bother checking, `docker compose` is the new version, while `docker-compose` is deprecated and will not be used for long

Currently, if you have Docker Desktop, it automatically creates an alias for `docker-compose` to call `docker compose`

**Comment by MarianoMolina** [comment]
Interesting to know. Didn't know docker-compose is deprecated tbh. Thanks!
